lab12/config/routes.rb
Rails.application.routes.draw do
  get 'numfinder/input'
  get 'numfinder/output'
  get 'translate/input'
  get 'translate/output'
  get 'sessions/exit'
  get 'sessions/create'
  root 'sessions#new'
  get 'users/index'
  get 'users/new'
  get 'users/xml'
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

lab12/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

lab12/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  def has_password?(submitted_password)
    password == submitted_password
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end
end

lab12/app/controllers/application_controller.rb
# frozen_string_literal: true

# class ApplicationController
class ApplicationController < ActionController::Base

  before_action :authenticate, except: %i[new create]

  def current_user
    @current_user ||= session[:current_user_id] &&
                      User.find_by_id(session[:current_user_id])
  end

  private

  def authenticate
    redirect_to root_path unless current_user
  end
end

lab12/app/controllers/numfinder_controller.rb
# frozen_string_literal: true

# com
class NumfinderController < ApplicationController
  def input; end

  def output
    @ent_num = params[:ch].to_i
    @bearb_num = @ent_num.to_s(2)
    @rev_bearb_num = @bearb_num.reverse
    @result = @rev_bearb_num.to_i(2)
  end
end

lab12/app/controllers/sessions_controller.rb
# frozen_string_literal: true

# class SessionsController
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user.nil?

      redirect_to '/sessions/new?message=Incorrect+login+or+password'
    else
      sign_in user
      redirect_to :numfinder_input
    end
  end

  def exit
    sign_out
    redirect_to :root
  end

  def sign_in(user)
    session[:current_user_id] = user.id
    self.current_user = user
  end

  def sign_out
    session[:current_user_id] = nil
    self.current_user = nil
  end

  attr_writer :current_user
end

lab12/app/controllers/translate_controller.rb
# frozen_string_literal: true

# class TranslateControlle
class TranslateController < ApplicationController
  def input; end

  def output
    @result_table = calculate(params[:ch])
  end

  def calculate(in_x)
    [in_x.to_i, in_x.to_i.to_s(2), in_x.to_i.to_s(2).reverse, in_x.to_i.to_s(2).reverse.to_i(2)]
  end
end

lab12/app/controllers/users_controller.rb
# frozen_string_literal: true

# class UsersController
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  def xml
    users = User.all.map do |user|
      { username: user.username, email: user.email, password_digest: user.password_digest }
    end
    render xml: users
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    if User.find_by(email: @user.email)
      redirect_to :root
      return
    end
    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User has been updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

lab12/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

lab12/app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

lab12/app/helpers/translate_helper.rb
# frozen_string_literal: true

module TranslateHelper
end

lab12/app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

lab12/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab12</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if User.find_by_id(session[:current_user_id]) %>
    <p>Current user:<%= User.find_by_id(session[:current_user_id]).username %></p>
    <% else %>
    <p>Not logged in</p>
    <% end %>
    <%= yield %>
  </body>
</html>

lab12/app/views/numfinder/input.html.erb
<h3>You are now viewing page, that is located in app/views</h3>
<%= form_tag("/numfinder/output", :method => "get") do %>
  <%= label_tag("Enter the number for convertation:") %>
  <%= number_field_tag(:ch, nil, min: 0, step: 1)%> <br/>
  <%= submit_tag("Convert") %>
<% end %>
<%= button_to "List", "/users/index", method: :get %>
<%= button_to "Logout", "/sessions/exit", method: :get %>

lab12/app/views/numfinder/output.html.erb
<strong><em>you are now viewing file that is located in app/views</em></strong>
<table>
  <tr>
    <th>iteration</th>
    <th>value of the proceeded element</th>
  </tr>
  <tr>
    <td>entered number</td>
    <td><%=@ent_num %></td>
  </tr>
  <tr>
    <td>binary digit</td>
    <td><%=@bearb_num %></td>
  </tr>
  <tr>
    <td>reversed binary number</td>
    <td><%=@rev_bearb_num %></td>
  </tr>
  <tr>
    <td>reversed decimal number</td>
    <td><%=@result %></td>
  </tr>
</table>
<%= button_to "New", "/numfinder/input", method: :get %>
<%= button_to "List", "/users/index", method: :get %>
<%= button_to "Logout", "/sessions/exit", method: :get %>

lab12/app/views/translate/input.html.erb
<h3>Добро пожаловать на страницу перевода чисел</h3>
<%= form_tag("/translate/output", :method => "get") do %>
  <%= label_tag("Введите число:") %>
  <%= number_field_tag(:ch, nil, min: 0, step: 1)%> <br/>
  <%= submit_tag("Перевести") %>
<% end %>
<%= link_to "To userlist", users_index_path %>
<%= link_to "Log out", sessions_exit_path %>

lab12/app/views/translate/output.html.erb
<h3>Таблица действий</h3>
<table>
  <tr>
    <th>Шаг</th>
    <th>Значение</th>
  </tr>
  <tr>
    <td>Введенное число</td>
    <td><%=@result_table[0] %></td>
  </tr>
  <tr>
    <td>Число в двоичном виде</td>
    <td><%=@result_table[1] %></td>
  </tr>
  <tr>
    <td>Реверс числа в двоичном виде</td>
    <td><%=@result_table[2]%></td>
  </tr>
  <tr>
    <td>Реверс числа в десятичном виде</td>
    <td><%=@result_table[3] %></td>
  </tr>
</table>
<%= link_to "Repeat translation", :translate_input %>
<%= link_to "To userlist", users_index_path %>
<%= link_to "Log out", sessions_exit_path %>

lab12/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

lab12/app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

lab12/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= button_to "list", "/users", method: :get %>
  <%= link_to "Show this user", @user %>
</div>

lab12/app/views/users/index.html.erb
<h1>Users</h1>

<table>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Redact</th>
    </tr>
  </thead>

    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
</table>

<%= button_to "Add user", "/users/new", method: :get %>
<%= button_to "Convertation", "/numfinder/input", method: :get %>
<%= button_to "Destroy this user", User.find_by_id(session[:current_user_id]), method: :delete %>
<%= link_to "XML", users_xml_path %>
<%= link_to "Sign", root_path %>

lab12/app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= button_to "Signin", "/users", method: :get %>
</div>

lab12/app/views/users/show.html.erb
<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  
  <%= button_to "list", "/users", method: :get %>
  <%= button_to "Destroy this user", @user, method: :delete %>
</div>