lab11/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'num_finder/input'
  get 'num_finder/output'
  get 'num_finder/xml'
  get 'num_finder/json'
  root to: redirect('num_finder/input')
end

lab11/app/models/result.rb
# frozen_string_literal: true

class Result < ApplicationRecord
  validates :in, :numericality => { :greater_than_or_equal_to => 0 }

  validates :in, uniqueness: true
end

lab11/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

lab11/app/controllers/num_finder_controller.rb
# frozen_string_literal: true

# com
class NumFinderController < ApplicationController
  def input; end

  def output
    result = Result.find_by(in: params[:ch].to_i)
    if result
      @result_table = ActiveSupport::JSON.decode(result.out)
    else
      @result_table = calculate(params[:ch])
      (Result.create in: params[:ch].to_i, out: ActiveSupport::JSON.encode(@result_table)).save
    end
  end
  def json
    @db = Result.all
    render json: @db
  end

  def xml
    results = Result.all.map do |result|
      { out: result.in, output: result.out }
    end
    render xml: results
  end

  private

  def calculate(in_x)
    [in_x.to_i, in_x.to_i.to_s(2), in_x.to_i.to_s(2).reverse, in_x.to_i.to_s(2).reverse.to_i(2)]
  end
end

lab11/app/helpers/application_helper.rb
# frozen_string_literal: true

# com
module ApplicationHelper
end

lab11/app/helpers/num_finder_helper.rb
# frozen_string_literal: true

# com
module NumFinderHelper
end

lab11/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab8</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

lab11/app/views/num_finder/input.html.erb
<h3>You are now viewing page, that is located in app/views</h3>
<%= form_tag("/num_finder/output", :method => "get") do %>
  <%= label_tag("Enter the number for convertation:") %>
  <%= number_field_tag(:ch, nil, min: 0, step: 1)%> <br/>
  <%= submit_tag("Convert") %>
<% end %>
<%= link_to "JSON", num_finder_json_path %><br>
<%= link_to "XML", num_finder_xml_path %>

lab11/app/views/num_finder/output.html.erb
<strong><em>you are now viewing file that is located in app/views</em></strong>
<table>
  <tr>
    <th>iteration</th>
    <th>value of the proceeded element</th>
  </tr>
  <tr>
    <td>entered number</td>
    <td><%=@result_table[0] %></td>
  </tr>
  <tr>
    <td>binary digit</td>
    <td><%=@result_table[1] %></td>
  </tr>
  <tr>
    <td>reversed binary number</td>
    <td><%=@result_table[2] %></td>
  </tr>
  <tr>
    <td>reversed decimal number</td>
    <td><%=@result_table[3] %></td>
  </tr>
</table>
<%= button_to "New", "/num_finder/input", method: :get %>